packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@types/express': ^5.0.1
  better-auth: ^1.4.5
  dotenv: ^17.2.2

onlyBuiltDependencies: '[''sharp'']'
